### ISSUE TITLE
Failure to load on minimal system

### ISSUE THREAD

**Issue by m00natic** [40ants/weblocks-ui#4]
After the recent README update (thanks!) trying to load weblocks on a
minimal centos docker image with roswell and sbcl-bin however stops
at:

* (ql:quickload "weblocks-ui")

debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD "main thread" RUNNING {1000510083}>: Error while trying to load definition for system weblocks-ui from pathname /root/.roswell/lisp/quicklisp/dists/ultralisp/software\
/40ants-weblocks-ui-20200204200122/weblocks-ui.asd: READ error during LOAD: :ASCII stream decoding error on #<SB-SYS:FD-STREAM for "file /root/.roswell/lisp/quicklisp/dists/ultralisp/software/40ants-weblocks-ui-20200204200122/README.rst\
" {10062F8AE3}>: the octet sequence #(226) cannot be decoded.(in form starting at line: 1, column: 0, position: 0)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT                        ] Abort loading file "/root/.roswell/lisp/quicklisp/dists/ultralisp/software/40ants-weblocks-ui-20200204200122/weblocks-ui.asd".
  1: [RETRY                        ] Retry #<DEFINE-OP > on #<PACKAGE-INFERRED-SYSTEM "weblocks-ui">.
  2: [ACCEPT                       ] Continue, treating #<DEFINE-OP > on #<PACKAGE-INFERRED-SYSTEM "weblocks-ui"> as having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
  5:                                 Retry ASDF operation.
  6:                                 Retry ASDF operation after resetting the configuration.
  7:                                 Give up on "weblocks-ui"
  8:                                 Exit debugger, returning to top level.

((FLET "H0" :IN PERFORM) #<SB-C::INPUT-ERROR-IN-LOAD {10062FBEF3}>)
   error finding frame source: Bogus form-number: the source file has probably changed too much to cope with.
   source: NIL
0]

**Comment by vindarel** [comment]
I'll have a guess: probably a unicode character that I introduced here, being so used to type it:

```
   (defwiget my-widget (weblocsk-ui:ui-widget)
     ((…))
     ;; ^^ this one character
```

Can you confirm? In any case, sorry :D 

You could also try

    (setf sb-impl::*default-external-format* :utf-8)

in `~/.sbclrc`.

**Comment by vindarel** [comment]
I fixed the typo.

**Comment by m00natic** [comment]
Yes, it's the unicode ellipsis there. Thank you for changing it and
even more for the tip. I adjusted my scripts accordingly not to
have issues of this sort in the future. Feel a little guilty for
making you change what was actually fine README ¯\_(ツ)_/¯

**Comment by vindarel** [comment]
most of all, thanks for the report :)
